### ISSUE TITLE
Framework to build the website

### ISSUE THREAD

**Issue by verri** [dnaya-org/dnaya-org.github.io#1]
I suggest either [Jekyll](https://jekyllrb.com/) or [Hugo](https://gohugo.io/).

My preference is Hugo.

Is there another option?

**Comment by ryukinix** [comment]
Hi @verri, I have experience with jekyll, as I wrote my personal website https://lerax.me, but currently jekyll has a lot of legacy stuff not so greatly maintained. I maintain my personal website with jekyll since 2016 and I had problems. I know a friend and some projects that used Hugo with success, simplicity and great performance. I vote for Hugo too.

About another options, there is, but I think is not relevant as `jekyll` and `Hugo`.

**Comment by verri** [comment]
Hugo it is.

Any opinion on the [theme](https://themes.gohugo.io/)?

**Comment by ryukinix** [comment]
Considering our objectives:

- Great adoption from a large user base (academic, market, open source)
- Algorithmic usage oriented

I vote for https://themes.gohugo.io/hugo-theme-learn/. It's seems a great theme oriented of the process of showing how to use things, how to setup, config, with code examples and so on. I think is a good choice for us.

Take a look and let me know what you think

**Comment by verri** [comment]
No objections. It fits.

**Comment by ryukinix** [comment]
#3 it's done. We are alive for testing.
